### ISSUE TITLE
GREAT - relative file paths

### ISSUE THREAD

**Issue by franfranfranfran** [IlyaGrigo/prj-rev-bwfs-dasmoto#1]
https://github.com/IlyaGrigo/prj-rev-bwfs-dasmoto/blob/master/DasmotoArt%26Craft/index.html#L14

https://github.com/IlyaGrigo/prj-rev-bwfs-dasmoto/blob/master/DasmotoArt%26Craft/resources/css/index.css#L10

excellent job saving your image files locally and then using relative file paths to link from your html and css. to further organized things in your project folder, consider placing your images in a separate images folder within resources.

**Comment by IlyaGrigo** [comment]
Fixed it in my updated version.
