### ISSUE TITLE
SUBTLETY - html entities

### ISSUE THREAD

**Issue by franfranfranfran** [IlyaGrigo/prj-rev-bwfs-dasmoto#3]
https://github.com/IlyaGrigo/prj-rev-bwfs-dasmoto/blob/master/DasmotoArt%26Craft/index.html#L10

consider using an html entity to represent the & special character to ensure that the character displays correctly across all browsers. more info can be found here - https://www.w3schools.com/html/html_entities.asp

**Comment by IlyaGrigo** [comment]
Thank you for indication of a defect.
Fixed it in my updated version.
