### ISSUE TITLE
GREAT - div structure

### ISSUE THREAD

**Issue by franfranfranfran** [IlyaGrigo/prj-rev-bwfs-dasmoto#4]
https://github.com/IlyaGrigo/prj-rev-bwfs-dasmoto/blob/master/DasmotoArt%26Craft/index.html#L12-L17

great idea to use divs with class names to keep your html organized and well-structured. consider placing a line break between each main content section to help with readability / make each chunk more distinct. more info about html styling in general can be found here - https://www.w3schools.com/html/html5_syntax.asp

**Comment by IlyaGrigo** [comment]
Fixed it in my updated version.
